#pragma config(Sensor, dgtl1,  LEDgreen,       sensorLEDtoVCC)
#pragma config(Sensor, dgtl2,  LEDyellow,      sensorLEDtoVCC)
#pragma config(Sensor, dgtl3,  LEDred,         sensorLEDtoVCC)
#pragma config(Sensor, dgtl4,  jumperrController, sensorDigitalIn)
#pragma config(Motor,  port1,           motorRight,    tmotorVex393_HBridge, openLoop, driveRight)
#pragma config(Motor,  port2,           clawLift,      tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port9,           clawControl,   tmotorVex269_MC29, openLoop)
#pragma config(Motor,  port10,          motorLeft,     tmotorVex393_HBridge, openLoop, driveLeft)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

void automate() {
		motor[motorRight] = 200; //Right Motor Turning at 80 Rotations Per Minute
		motor[motorLeft] = 127; //Left Motor Turning at 80 RPM

		wait1Msec(6000);

		motor[motorRight] = 80; //Right Motor Turning at 0 Rotations Per Minute
		motor[motorLeft] = 80; //Left Motor Turning at 0 RPM

	}
task main()
{
	int changeValue  = 40;
	int mode = 1;
	while (true)
	{
		if ( mode == 1){
			motor[motorLeft] = vexRT[Ch3]/2 - vexRT[Ch4]/2;
			motor[motorRight] = vexRT[Ch3]/2 + vexRT[Ch4]/2;
		}
		else if (mode == 0) {
			motor[motorLeft] = vexRT[Ch2]*2;
			motor[motorRight] = vexRT[Ch3]*2; // remove *2 to reduce stick drift
		}

		if(vexRT[Btn6U] == 1) {
			motor[clawLift] = changeValue;
		}
		else if(vexRT[Btn6D] == 1) {
			motor[clawLift] = -1 * changeValue;
		}
		else {
			motor[clawLift] = 0;
		}
		if (vexRT[Btn8L]) {
			automate();
		}
		if(vexRT[Btn5U] == 1) {
			motor[clawControl] = changeValue;
		}
		else if(vexRT[Btn5D] == 1) {
			motor[clawControl] = -1 * changeValue;
		}
		else {
			motor[clawControl] = 0;
		}

		if(vexRT[Btn7L] == 1) {
			changeValue = 127;

		}
		else if(vexRT[Btn7R] == 1) {
			changeValue = 40;
		}

		if (changeValue == 40) {
			SensorValue[dgtl1] = 0;
			SensorValue[dgtl2] = 1;
		}
		else if (changeValue == 127) {
			SensorValue[dgtl1] = 1;
			SensorValue[dgtl2] = 0;
		}

		if (SensorValue[dgtl4] == 1) {
			mode = 1;
		}
		else if (SensorValue[dgtl4] == 0) {
			mode = 0;
		}
		SensorValue[dgtl3] = mode;


	}




}
